config:
  token:
    existingSecret: firezone-secret
logLevel: info
image:
  repository: ghcr.io/firezone/gateway
  tag: 1.4.18@sha256:d8229137221dff80e2e7103a71f6f25462ab19bb319d6ccbb0f7f844059b9eff
