config:
  token:
    existingSecret: firezone-secret
logLevel: info
image:
  repository: ghcr.io/firezone/gateway
  tag: 1.4.19@sha256:8432f27d3376b600f9a4374d0174e20866363c26b759562a33714db1b1d9b05b
